credentials:
  usernames:
    firstUser:
      email: firstuser@gmail.com
      name: username1
      password: $2b$12$iG5usgoEotI0y.eVWlGN7ez13BM8rZ9m907Tm/ELS.BwY395ZWUUi #12345 # To be replaced with hashed password
    secondUser:
      email: seconduser@gmail.com
      name: username2
      password: $2b$12$YgZkH.enO.djF1eMkLelTeM6WvlosOorFAKLkQqjktZtK1J2VUK3.  #111213 # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
    - my@gmail.com

